name: rss_feed
description: A feed manager to centralize your sources.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: 0.12.2
  xml: 4.5.1
  timeago: 2.0.27
  intl: 0.16.1
  provider: 4.3.2+2
  sqflite: 1.3.1+2
  url_launcher: 5.7.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: 0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/newspaper.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/dummy-image.jpg
