name: rss_feed
description: RSS feed reader

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.3
  infinite_scroll_pagination: ^3.0.1
  intl: ^0.17.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  timeago: ^3.0.2
  url_launcher: ^6.0.3
  webfeed: ^0.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/scroll.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/dummy-image.jpg